# 端口号
server:
  port: 8100

spring:
  # 服务名
  application:
    name: gateway
  # 当前环境
  profiles:
    active: dev
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      # 网关
      discovery:
        locator:
          enabled: true
      # 路由
      routes:
        - id: admin-api
          uri: lb://admin-api
          predicates:
            - Path=/admin/**
        - id: education-api
          uri: lb://education-api
          predicates:
            - Path=/education/**
        - id: extension-api
          uri: lb://extension-api
          predicates:
            - Path=/extension/**
        - id: oss-api
          uri: lb://oss-api
          predicates:
            - Path=/oss/**
        - id: vod-api
          uri: lb://vod-api
          predicates:
            - Path=/vod/**

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
    connection-timeout: 20000
    connection-timer-repeat: 30000
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000


