# 端口号
server:
  port: 8002

spring:
  # 服务名
  application:
    name: education-api
  # 当前环境
  profiles:
    active: dev
    # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xzx-oep?serverTimezone=GMT%2B8
    username: root
    password: xzx123
  # Json格式化时间
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 设置最大文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 单次请求总文件大小
      max-request-size: 100MB
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # redis
  redis:
    timeout: 30000ms
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        # 最大连接数
        max-active: 1024
        # 最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 200
        # 最小空闲连接
        min-idle: 5

# mybatis-plus日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/xml/*.xml

feign:
  httpclient:
    enabled: true

